server:
  port: 8080

rabbitmq:
  queue:
    name:
      order: order_queue
      email: email_queue
  exchange:
    name: order_exchange
  routing:
    key:
      order: order_routing_key
      email: email_routing_key
